kind: project
metadata:
  name: parcheggi
  created: '2023-12-21T16:37:58.071000'
spec:
  functions:
  - url: src/download-all.py
    name: download-all
    kind: job
    image: mlrun/mlrun
    handler: downloader
  - url: src/extract_parkings.py
    name: extract-parkings
    kind: job
    image: mlrun/mlrun
    handler: extract_parkings
  - url: src/aggregate_parkings.py
    name: aggregate-parkings
    kind: job
    image: mlrun/mlrun
    handler: aggregate_parkings
  - url: src/parkings_last_data.py
    name: extract-parkings-latest
    kind: job
    image: mlrun/mlrun
    handler: parkings_last_data
    requirements:
    - sqlalchemy
    - psycopg2-binary
  - url: src/parkings_to_db.py
    name: to-db
    kind: job
    image: mlrun/mlrun
    handler: to_db
    requirements:
    - sqlalchemy
    - psycopg2-binary
  - url: src/train_predictors.py
    name: predict-day
    kind: job
    image: mlrun/mlrun
    handler: predict_day
    requirements:
    - sqlalchemy
    - psycopg2-binary
    - statsmodels
  workflows:
  - path: ./src/data_update_pipeline.py
    name: data-update-pipeline
    handler: pipeline
  artifacts: []
  conda: ''
  source: git://gitlab.hpc.cineca.it/dt-data-projects/gdb-project-parkings.git
  origin_url: git://github.com/scc-digitalhub/gdb-project-parkings.git#refs/heads/main
  load_source_on_run: false
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
